import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";

import { LoaderProvider } from "./loader-context";
import Navbar from "@/components/navbar";

// fonts
const inter = Inter({
    subsets: ["latin"],
    variable: "--font-cta", // Defines the CSS variable name automatically
    display: "swap",
});

const spaceGrotesk = Space_Grotesk({
    subsets: ["latin"],
    variable: "--font-main", // Defines the CSS variable name automatically
    display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
        // fonts
		<html lang="en" className={`${spaceGrotesk.className} ${inter.variable}`}>
            {/*100px gutter (left and right) on medium+ sizes*/}
			<body className={`px-4 md:px-[80px] lg:px-[160px]`}>
				<ViewTransitions>
					<LoaderProvider>
                        <Navbar />
                        {children}
                    </LoaderProvider>
				</ViewTransitions>
			</body>
		</html>
	);
}
