import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";

import { LoaderProvider } from "./loader-context";
import Navbar from "@/components/navbar";

const dmSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${dmSans.variable} antialiased`}>
				<ViewTransitions>
					<LoaderProvider>
                        <Navbar />
                        {children}
                    </LoaderProvider>
				</ViewTransitions>
			</body>
		</html>
	);
}
